FUNCTION-POOL zfi_0040dte.                  "MESSAGE-ID ..

* INCLUDE LZFI_0040DTED...                   " Local class definition
TYPES: BEGIN OF ty_t001,
         bukrs TYPE t001-bukrs,
         wfvar TYPE t001-wfvar,
       END OF ty_t001.
DATA: lt_ekko TYPE STANDARD TABLE OF ekko WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_lfb1_oc TYPE STANDARD TABLE OF lfb1 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_ekpo TYPE STANDARD TABLE OF ekpo WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_ekkn TYPE STANDARD TABLE OF ekkn WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_afko TYPE STANDARD TABLE OF afko WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_proj TYPE STANDARD TABLE OF proj WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_zdte_posfact_oc TYPE STANDARD TABLE OF ztfi_0075 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_zdte_posfact TYPE STANDARD TABLE OF ztfi_0075 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_zdte_cldoc TYPE STANDARD TABLE OF ztfi_0001b WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: s_tipodte LIKE lfb1-zzdte_tipo.
DATA: lt_zcb_recfactprov TYPE STANDARD TABLE OF ztfi_0074 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: ls_salidag TYPE zefi_0026.
DATA: estatus TYPE char01.
DATA: ti_vbwf16 TYPE STANDARD TABLE OF vbwf16 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lt_t001 TYPE STANDARD TABLE OF ty_t001 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: lv_registro_pos TYPE  sy-tabix.
DATA: lt_zdt_recref TYPE STANDARD TABLE OF ztfi_0077 WITH NON-UNIQUE DEFAULT KEY WITH HEADER LINE.
DATA: ti_essr      TYPE STANDARD TABLE OF zty_ess WITH HEADER LINE WITH NON-UNIQUE DEFAULT KEY.
DATA: lt_docele TYPE STANDARD TABLE OF ztfi_0074 WITH HEADER LINE WITH NON-UNIQUE DEFAULT KEY.
DATA: lt_factmm TYPE STANDARD TABLE OF zcds_factmm  WITH HEADER LINE WITH NON-UNIQUE DEFAULT KEY.
DATA: gv_fechac TYPE sy-datum.
DATA: ok_code       TYPE syucomm.
