*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGF_ZTFI_0001BTOP.                " Global Data
  INCLUDE LZGF_ZTFI_0001BUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGF_ZTFI_0001BF00                      . " subprograms
  INCLUDE LZGF_ZTFI_0001BI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGF_ZTFI_0001BF...                " Subprograms
* INCLUDE LZGF_ZTFI_0001BO...                " PBO-Modules
* INCLUDE LZGF_ZTFI_0001BI...                " PAI-Modules
