*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVFI_0075.......................................*
FORM GET_DATA_ZVFI_0075.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTFI_0075 WHERE
(VIM_WHERETAB) .
    CLEAR ZVFI_0075 .
ZVFI_0075-MANDT =
ZTFI_0075-MANDT .
ZVFI_0075-BUKRS =
ZTFI_0075-BUKRS .
ZVFI_0075-LIFNR =
ZTFI_0075-LIFNR .
ZVFI_0075-XBLNR =
ZTFI_0075-XBLNR .
ZVFI_0075-TIPODTE =
ZTFI_0075-TIPODTE .
ZVFI_0075-POS =
ZTFI_0075-POS .
ZVFI_0075-EBELN =
ZTFI_0075-EBELN .
ZVFI_0075-EBELP =
ZTFI_0075-EBELP .
<VIM_TOTAL_STRUC> = ZVFI_0075.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_0075 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_0075.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_0075-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTFI_0075 WHERE
  BUKRS = ZVFI_0075-BUKRS AND
  LIFNR = ZVFI_0075-LIFNR AND
  XBLNR = ZVFI_0075-XBLNR AND
  TIPODTE = ZVFI_0075-TIPODTE AND
  POS = ZVFI_0075-POS .
    IF SY-SUBRC = 0.
    DELETE ZTFI_0075 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTFI_0075 WHERE
  BUKRS = ZVFI_0075-BUKRS AND
  LIFNR = ZVFI_0075-LIFNR AND
  XBLNR = ZVFI_0075-XBLNR AND
  TIPODTE = ZVFI_0075-TIPODTE AND
  POS = ZVFI_0075-POS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTFI_0075.
    ENDIF.
ZTFI_0075-MANDT =
ZVFI_0075-MANDT .
ZTFI_0075-BUKRS =
ZVFI_0075-BUKRS .
ZTFI_0075-LIFNR =
ZVFI_0075-LIFNR .
ZTFI_0075-XBLNR =
ZVFI_0075-XBLNR .
ZTFI_0075-TIPODTE =
ZVFI_0075-TIPODTE .
ZTFI_0075-POS =
ZVFI_0075-POS .
ZTFI_0075-EBELN =
ZVFI_0075-EBELN .
ZTFI_0075-EBELP =
ZVFI_0075-EBELP .
    IF SY-SUBRC = 0.
    UPDATE ZTFI_0075 ##WARN_OK.
    ELSE.
    INSERT ZTFI_0075 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_0075-UPD_FLAG,
STATUS_ZVFI_0075-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVFI_0075.
  SELECT SINGLE * FROM ZTFI_0075 WHERE
BUKRS = ZVFI_0075-BUKRS AND
LIFNR = ZVFI_0075-LIFNR AND
XBLNR = ZVFI_0075-XBLNR AND
TIPODTE = ZVFI_0075-TIPODTE AND
POS = ZVFI_0075-POS .
ZVFI_0075-MANDT =
ZTFI_0075-MANDT .
ZVFI_0075-BUKRS =
ZTFI_0075-BUKRS .
ZVFI_0075-LIFNR =
ZTFI_0075-LIFNR .
ZVFI_0075-XBLNR =
ZTFI_0075-XBLNR .
ZVFI_0075-TIPODTE =
ZTFI_0075-TIPODTE .
ZVFI_0075-POS =
ZTFI_0075-POS .
ZVFI_0075-EBELN =
ZTFI_0075-EBELN .
ZVFI_0075-EBELP =
ZTFI_0075-EBELP .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_0075 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_0075-BUKRS TO
ZTFI_0075-BUKRS .
MOVE ZVFI_0075-LIFNR TO
ZTFI_0075-LIFNR .
MOVE ZVFI_0075-XBLNR TO
ZTFI_0075-XBLNR .
MOVE ZVFI_0075-TIPODTE TO
ZTFI_0075-TIPODTE .
MOVE ZVFI_0075-POS TO
ZTFI_0075-POS .
MOVE ZVFI_0075-MANDT TO
ZTFI_0075-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTFI_0075'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTFI_0075 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTFI_0075'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
