*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVFI_0087.......................................*
FORM GET_DATA_ZVFI_0087.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTFI_0087 WHERE
(VIM_WHERETAB) .
    CLEAR ZVFI_0087 .
ZVFI_0087-MANDT =
ZTFI_0087-MANDT .
ZVFI_0087-ZDTE_TIPO =
ZTFI_0087-ZDTE_TIPO .
ZVFI_0087-REPID =
ZTFI_0087-REPID .
ZVFI_0087-GRPNO =
ZTFI_0087-GRPNO .
ZVFI_0087-SEC =
ZTFI_0087-SEC .
ZVFI_0087-VTEXT1 =
ZTFI_0087-VTEXT1 .
ZVFI_0087-ST_OK =
ZTFI_0087-ST_OK .
ZVFI_0087-ST_NOK =
ZTFI_0087-ST_NOK .
ZVFI_0087-ACTIVO =
ZTFI_0087-ACTIVO .
    SELECT SINGLE * FROM ZTFI_0086 WHERE
ZDTE_TIPO = ZTFI_0087-ZDTE_TIPO AND
REPID = ZTFI_0087-REPID .
    IF SY-SUBRC EQ 0.
ZVFI_0087-VTEXT =
ZTFI_0086-VTEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFI_0087.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_0087 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_0087.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_0087-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTFI_0087 WHERE
  ZDTE_TIPO = ZVFI_0087-ZDTE_TIPO AND
  REPID = ZVFI_0087-REPID AND
  GRPNO = ZVFI_0087-GRPNO .
    IF SY-SUBRC = 0.
    DELETE ZTFI_0087 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTFI_0087 WHERE
  ZDTE_TIPO = ZVFI_0087-ZDTE_TIPO AND
  REPID = ZVFI_0087-REPID AND
  GRPNO = ZVFI_0087-GRPNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTFI_0087.
    ENDIF.
ZTFI_0087-MANDT =
ZVFI_0087-MANDT .
ZTFI_0087-ZDTE_TIPO =
ZVFI_0087-ZDTE_TIPO .
ZTFI_0087-REPID =
ZVFI_0087-REPID .
ZTFI_0087-GRPNO =
ZVFI_0087-GRPNO .
ZTFI_0087-SEC =
ZVFI_0087-SEC .
ZTFI_0087-VTEXT1 =
ZVFI_0087-VTEXT1 .
ZTFI_0087-ST_OK =
ZVFI_0087-ST_OK .
ZTFI_0087-ST_NOK =
ZVFI_0087-ST_NOK .
ZTFI_0087-ACTIVO =
ZVFI_0087-ACTIVO .
    IF SY-SUBRC = 0.
    UPDATE ZTFI_0087 ##WARN_OK.
    ELSE.
    INSERT ZTFI_0087 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_0087-UPD_FLAG,
STATUS_ZVFI_0087-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVFI_0087.
  SELECT SINGLE * FROM ZTFI_0087 WHERE
ZDTE_TIPO = ZVFI_0087-ZDTE_TIPO AND
REPID = ZVFI_0087-REPID AND
GRPNO = ZVFI_0087-GRPNO .
ZVFI_0087-MANDT =
ZTFI_0087-MANDT .
ZVFI_0087-ZDTE_TIPO =
ZTFI_0087-ZDTE_TIPO .
ZVFI_0087-REPID =
ZTFI_0087-REPID .
ZVFI_0087-GRPNO =
ZTFI_0087-GRPNO .
ZVFI_0087-SEC =
ZTFI_0087-SEC .
ZVFI_0087-VTEXT1 =
ZTFI_0087-VTEXT1 .
ZVFI_0087-ST_OK =
ZTFI_0087-ST_OK .
ZVFI_0087-ST_NOK =
ZTFI_0087-ST_NOK .
ZVFI_0087-ACTIVO =
ZTFI_0087-ACTIVO .
    SELECT SINGLE * FROM ZTFI_0086 WHERE
ZDTE_TIPO = ZTFI_0087-ZDTE_TIPO AND
REPID = ZTFI_0087-REPID .
    IF SY-SUBRC EQ 0.
ZVFI_0087-VTEXT =
ZTFI_0086-VTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_0087-VTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_0087 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_0087-ZDTE_TIPO TO
ZTFI_0087-ZDTE_TIPO .
MOVE ZVFI_0087-REPID TO
ZTFI_0087-REPID .
MOVE ZVFI_0087-GRPNO TO
ZTFI_0087-GRPNO .
MOVE ZVFI_0087-MANDT TO
ZTFI_0087-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTFI_0087'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTFI_0087 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTFI_0087'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFI_0087 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTFI_0087-MANDT =
ZVFI_0087-MANDT .
ZTFI_0087-ZDTE_TIPO =
ZVFI_0087-ZDTE_TIPO .
ZTFI_0087-REPID =
ZVFI_0087-REPID .
ZTFI_0087-GRPNO =
ZVFI_0087-GRPNO .
ZTFI_0087-SEC =
ZVFI_0087-SEC .
ZTFI_0087-VTEXT1 =
ZVFI_0087-VTEXT1 .
ZTFI_0087-ST_OK =
ZVFI_0087-ST_OK .
ZTFI_0087-ST_NOK =
ZVFI_0087-ST_NOK .
ZTFI_0087-ACTIVO =
ZVFI_0087-ACTIVO .
    SELECT SINGLE * FROM ZTFI_0086 WHERE
ZDTE_TIPO = ZTFI_0087-ZDTE_TIPO AND
REPID = ZTFI_0087-REPID .
    IF SY-SUBRC EQ 0.
ZVFI_0087-VTEXT =
ZTFI_0086-VTEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_0087-VTEXT .
    ENDIF.
ENDFORM.
