*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGF_ZTFI_0074TOP.                 " Global Data
  INCLUDE LZGF_ZTFI_0074UXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGF_ZTFI_0074F00                       . " subprograms
  INCLUDE LZGF_ZTFI_0074I00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGF_ZTFI_0074F...                 " Subprograms
* INCLUDE LZGF_ZTFI_0074O...                 " PBO-Modules
* INCLUDE LZGF_ZTFI_0074I...                 " PAI-Modules

INCLUDE LZGF_ZTFI_0074F01.
