*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGF_RECFACTMAPTOP.                " Global Data
  INCLUDE LZGF_RECFACTMAPUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGF_RECFACTMAPF00                      . " subprograms
  INCLUDE LZGF_RECFACTMAPI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGF_RECFACTMAPF...                " Subprograms
* INCLUDE LZGF_RECFACTMAPO...                " PBO-Modules
* INCLUDE LZGF_RECFACTMAPI...                " PAI-Modules
